// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings_queries.sql

package db

import (
	"context"
	"database/sql"
)

const countScanFindings = `-- name: CountScanFindings :one
SELECT COUNT(*) FROM scan_findings WHERE scan_id = ?
`

func (q *Queries) CountScanFindings(ctx context.Context, scanID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanFindings, scanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertScanFinding = `-- name: InsertScanFinding :exec
INSERT INTO scan_findings (scan_id, url, scan_time, content_type, content_length, last_modified, category, interest_score, tags)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScanFindingParams struct {
	ScanID        string
	Url           string
	ScanTime      string
	ContentType   string
	ContentLength int64
	LastModified  sql.NullString
	Category      string
	InterestScore int64
	Tags          string
}

func (q *Queries) InsertScanFinding(ctx context.Context, arg InsertScanFindingParams) error {
	_, err := q.db.ExecContext(ctx, insertScanFinding,
		arg.ScanID,
		arg.Url,
		arg.ScanTime,
		arg.ContentType,
		arg.ContentLength,
		arg.LastModified,
		arg.Category,
		arg.InterestScore,
		arg.Tags,
	)
	return err
}

const listScanFindings = `-- name: ListScanFindings :many
SELECT id, scan_id, url, scan_time, content_type, content_length, last_modified, category, interest_score, tags FROM scan_findings WHERE scan_id = ? ORDER BY url ASC
`

func (q *Queries) ListScanFindings(ctx context.Context, scanID string) ([]ScanFinding, error) {
	rows, err := q.db.QueryContext(ctx, listScanFindings, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanFinding
	for rows.Next() {
		var i ScanFinding
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.Url,
			&i.ScanTime,
			&i.ContentType,
			&i.ContentLength,
			&i.LastModified,
			&i.Category,
			&i.InterestScore,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
