// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Scan struct {
	ScanID        string
	Url           string
	Status        string
	CreatedAt     string
	UpdatedAt     string
	CompletedAt   sql.NullString
	Result        sql.NullString
	FailureReason sql.NullString
}

type ScanFinding struct {
	ID            int64
	ScanID        string
	Url           string
	ScanTime      string
	ContentType   string
	ContentLength int64
	LastModified  sql.NullString
	Category      string
	InterestScore int64
	Tags          string
}
