// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const completeScan = `-- name: CompleteScan :exec
UPDATE scans
SET status = 'DONE', result = ?, completed_at = datetime('now'), updated_at = datetime('now')
WHERE scan_id = ?
`

type CompleteScanParams struct {
	Result sql.NullString
	ScanID string
}

func (q *Queries) CompleteScan(ctx context.Context, arg CompleteScanParams) error {
	_, err := q.db.ExecContext(ctx, completeScan, arg.Result, arg.ScanID)
	return err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (scan_id, url, status)
VALUES (?, ?, 'PENDING')
RETURNING scan_id, url, status, created_at, updated_at, completed_at, result, failure_reason
`

type CreateScanParams struct {
	ScanID string
	Url    string
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, createScan, arg.ScanID, arg.Url)
	var i Scan
	err := row.Scan(
		&i.ScanID,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Result,
		&i.FailureReason,
	)
	return i, err
}

const deleteScan = `-- name: DeleteScan :exec
DELETE FROM scans WHERE scan_id = ?
`

func (q *Queries) DeleteScan(ctx context.Context, scanID string) error {
	_, err := q.db.ExecContext(ctx, deleteScan, scanID)
	return err
}

const failScan = `-- name: FailScan :exec
UPDATE scans
SET status = 'FAILED', failure_reason = ?, completed_at = datetime('now'), updated_at = datetime('now')
WHERE scan_id = ?
`

type FailScanParams struct {
	FailureReason sql.NullString
	ScanID        string
}

func (q *Queries) FailScan(ctx context.Context, arg FailScanParams) error {
	_, err := q.db.ExecContext(ctx, failScan, arg.FailureReason, arg.ScanID)
	return err
}

const getScan = `-- name: GetScan :one
SELECT scan_id, url, status, created_at, updated_at, completed_at, result, failure_reason FROM scans WHERE scan_id = ?
`

func (q *Queries) GetScan(ctx context.Context, scanID string) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScan, scanID)
	var i Scan
	err := row.Scan(
		&i.ScanID,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Result,
		&i.FailureReason,
	)
	return i, err
}

const listScans = `-- name: ListScans :many
SELECT scan_id, url, status, created_at, updated_at, completed_at, result, failure_reason FROM scans ORDER BY created_at DESC
`

func (q *Queries) ListScans(ctx context.Context) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ScanID,
			&i.Url,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Result,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanStatus = `-- name: UpdateScanStatus :exec
UPDATE scans
SET status = ?, updated_at = datetime('now')
WHERE scan_id = ?
`

type UpdateScanStatusParams struct {
	Status string
	ScanID string
}

func (q *Queries) UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanStatus, arg.Status, arg.ScanID)
	return err
}
