// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package mullvad

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "strings"

type AmIConnected struct {
	// Ip corresponds to the JSON schema field "ip".
	Ip *string `json:"ip,omitempty" yaml:"ip,omitempty" mapstructure:"ip,omitempty"`

	// MullvadExitIp corresponds to the JSON schema field "mullvad_exit_ip".
	MullvadExitIp bool `json:"mullvad_exit_ip" yaml:"mullvad_exit_ip" mapstructure:"mullvad_exit_ip"`

	// MullvadExitIpHostname corresponds to the JSON schema field
	// "mullvad_exit_ip_hostname".
	MullvadExitIpHostname *string `json:"mullvad_exit_ip_hostname,omitempty" yaml:"mullvad_exit_ip_hostname,omitempty" mapstructure:"mullvad_exit_ip_hostname,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AmIConnected) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mullvad_exit_ip"]; raw != nil && !ok {
		return fmt.Errorf("field mullvad_exit_ip in AmIConnected: required")
	}
	type Plain AmIConnected
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = AmIConnected(plain)
	return nil
}
