// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package mullvad

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "strings"

type Location struct {
	// City corresponds to the JSON schema field "city".
	City string `json:"city" yaml:"city" mapstructure:"city"`

	// Country corresponds to the JSON schema field "country".
	Country string `json:"country" yaml:"country" mapstructure:"country"`

	// Latitude corresponds to the JSON schema field "latitude".
	Latitude float64 `json:"latitude" yaml:"latitude" mapstructure:"latitude"`

	// Longitude corresponds to the JSON schema field "longitude".
	Longitude float64 `json:"longitude" yaml:"longitude" mapstructure:"longitude"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Location) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["city"]; raw != nil && !ok {
		return fmt.Errorf("field city in Location: required")
	}
	if _, ok := raw["country"]; raw != nil && !ok {
		return fmt.Errorf("field country in Location: required")
	}
	if _, ok := raw["latitude"]; raw != nil && !ok {
		return fmt.Errorf("field latitude in Location: required")
	}
	if _, ok := raw["longitude"]; raw != nil && !ok {
		return fmt.Errorf("field longitude in Location: required")
	}
	type Plain Location
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Location(plain)
	return nil
}

type MullvadRelays struct {
	// Locations corresponds to the JSON schema field "locations".
	Locations MullvadRelaysLocations `json:"locations" yaml:"locations" mapstructure:"locations"`

	// Wireguard corresponds to the JSON schema field "wireguard".
	Wireguard WireguardEndpoints `json:"wireguard" yaml:"wireguard" mapstructure:"wireguard"`
}

type MullvadRelaysLocations map[string]Location

// UnmarshalJSON implements json.Unmarshaler.
func (j *MullvadRelays) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["locations"]; raw != nil && !ok {
		return fmt.Errorf("field locations in MullvadRelays: required")
	}
	if _, ok := raw["wireguard"]; raw != nil && !ok {
		return fmt.Errorf("field wireguard in MullvadRelays: required")
	}
	type Plain MullvadRelays
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MullvadRelays(plain)
	return nil
}

type Relay struct {
	// Active corresponds to the JSON schema field "active".
	Active bool `json:"active" yaml:"active" mapstructure:"active"`

	// Hostname corresponds to the JSON schema field "hostname".
	Hostname string `json:"hostname" yaml:"hostname" mapstructure:"hostname"`

	// IncludeInCountry corresponds to the JSON schema field "include_in_country".
	IncludeInCountry bool `json:"include_in_country" yaml:"include_in_country" mapstructure:"include_in_country"`

	// Ipv4AddrIn corresponds to the JSON schema field "ipv4_addr_in".
	Ipv4AddrIn string `json:"ipv4_addr_in" yaml:"ipv4_addr_in" mapstructure:"ipv4_addr_in"`

	// Ipv6AddrIn corresponds to the JSON schema field "ipv6_addr_in".
	Ipv6AddrIn string `json:"ipv6_addr_in" yaml:"ipv6_addr_in" mapstructure:"ipv6_addr_in"`

	// Location corresponds to the JSON schema field "location".
	Location string `json:"location" yaml:"location" mapstructure:"location"`

	// PublicKey corresponds to the JSON schema field "public_key".
	PublicKey string `json:"public_key" yaml:"public_key" mapstructure:"public_key"`

	// Weight corresponds to the JSON schema field "weight".
	Weight int `json:"weight" yaml:"weight" mapstructure:"weight"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Relay) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["active"]; raw != nil && !ok {
		return fmt.Errorf("field active in Relay: required")
	}
	if _, ok := raw["hostname"]; raw != nil && !ok {
		return fmt.Errorf("field hostname in Relay: required")
	}
	if _, ok := raw["include_in_country"]; raw != nil && !ok {
		return fmt.Errorf("field include_in_country in Relay: required")
	}
	if _, ok := raw["ipv4_addr_in"]; raw != nil && !ok {
		return fmt.Errorf("field ipv4_addr_in in Relay: required")
	}
	if _, ok := raw["ipv6_addr_in"]; raw != nil && !ok {
		return fmt.Errorf("field ipv6_addr_in in Relay: required")
	}
	if _, ok := raw["location"]; raw != nil && !ok {
		return fmt.Errorf("field location in Relay: required")
	}
	if _, ok := raw["public_key"]; raw != nil && !ok {
		return fmt.Errorf("field public_key in Relay: required")
	}
	if _, ok := raw["weight"]; raw != nil && !ok {
		return fmt.Errorf("field weight in Relay: required")
	}
	type Plain Relay
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = Relay(plain)
	return nil
}

type WireguardEndpoints struct {
	// Ipv4Gateway corresponds to the JSON schema field "ipv4_gateway".
	Ipv4Gateway string `json:"ipv4_gateway" yaml:"ipv4_gateway" mapstructure:"ipv4_gateway"`

	// Ipv6Gateway corresponds to the JSON schema field "ipv6_gateway".
	Ipv6Gateway string `json:"ipv6_gateway" yaml:"ipv6_gateway" mapstructure:"ipv6_gateway"`

	// PortRanges corresponds to the JSON schema field "port_ranges".
	PortRanges [][]int `json:"port_ranges" yaml:"port_ranges" mapstructure:"port_ranges"`

	// Relays corresponds to the JSON schema field "relays".
	Relays []Relay `json:"relays" yaml:"relays" mapstructure:"relays"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WireguardEndpoints) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ipv4_gateway"]; raw != nil && !ok {
		return fmt.Errorf("field ipv4_gateway in WireguardEndpoints: required")
	}
	if _, ok := raw["ipv6_gateway"]; raw != nil && !ok {
		return fmt.Errorf("field ipv6_gateway in WireguardEndpoints: required")
	}
	if _, ok := raw["port_ranges"]; raw != nil && !ok {
		return fmt.Errorf("field port_ranges in WireguardEndpoints: required")
	}
	if _, ok := raw["relays"]; raw != nil && !ok {
		return fmt.Errorf("field relays in WireguardEndpoints: required")
	}
	type Plain WireguardEndpoints
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WireguardEndpoints(plain)
	return nil
}
